parameters:
    doctrine_prefixr.prefixer.class: DoctrinePrefixr\Bundle\DoctrinePrefixrBundle\EventListener\TablePrefixSubscriber

services:
    doctrine.prefixr:
        class: %doctrine_prefixr.prefixer.class%
        public: false
        arguments: [%kernel.bundles%,%doctrine_prefixr.prefixes%]
        tags:
            - { name: doctrine.event_subscriber }
